picture_path: config_phantoms
preview:
  filename: 1
  original: 1.png
  sizes:
  - 1.png
  thumbnail: 1-thumbnail.png
pictures:
- filename: 1
  original: 1.png
  sizes:
  - 1.png
  thumbnail: 1-thumbnail.png
- filename: 2
  original: 2.png
  sizes:
  - 2.png
  thumbnail: 2-thumbnail.png
- filename: 3
  original: 3.png
  sizes:
  - 3.png
  thumbnail: 3-thumbnail.png
- filename: 4
  original: 4.png
  sizes:
  - 4.png
  thumbnail: 4-thumbnail.png
- filename: 5
  original: 5.png
  sizes:
  - 5.png
  thumbnail: 5-thumbnail.png
- filename: 6
  original: 6.png
  sizes:
  - 6.png
  thumbnail: 6-thumbnail.png
